// Generated by ts-to-zod
import { z } from "zod";

export const inlineApiKeyEntrySchema = z.object({
    key_from_env: z.string(),
    subject: z.string(),
    scopes: z.array(z.string()).optional()
});

export const apiKeyStoreConfigSchema = z.object({
    type: z.literal("inline"),
    keys: z.array(inlineApiKeyEntrySchema)
});

export const clientAuthGateConfigSchema = z.object({
    mode: z.union([z.literal("required"), z.literal("optional")]).optional(),
    mode_from_env: z.string().optional(),
    api_keys: apiKeyStoreConfigSchema.optional()
});

export const consentGateConfigSchema = z.object({
    required: z.boolean(),
    rules_version: z.string(),
    education_resource: z.string().optional(),
    rules_summary: z.string().optional(),
    max_age_days: z.number().optional(),
    identity_source: z.literal("profile_oauth"),
    template_path: z.string().optional(),
    template: z.string().optional(),
    labels: z.object({
        accept: z.string().optional(),
        submit: z.string().optional()
    }).optional()
});

export const upstreamMcpToolPolicySchema = z.object({
    allow: z.array(z.string()).optional(),
    deny: z.array(z.string()).optional()
});

export const upstreamMcpHttpStreamableTransportConfigSchema = z.object({
    type: z.literal("http-streamable"),
    url: z.string()
});

export const authTokenConfigSchema = z.object({
    type: z.union([z.literal("bearer"), z.literal("token"), z.literal("query"), z.literal("custom-header")]),
    header_name: z.string().optional(),
    query_param: z.string().optional()
});

export const upstreamMcpAuthConfigSchema = authTokenConfigSchema.extend({
    value_from_env: z.string().optional()
});

export const resourceFetchDefinitionSchema = z.object({
    source: z.union([z.literal("operation"), z.literal("composite")]),
    operation: z.string().optional(),
    composite_tool: z.string().optional(),
    parameter_mapping: z.record(z.string(), z.string()).optional(),
    result_path: z.string().optional(),
    cache_ttl_seconds: z.number().optional()
});

export const resourceAppsDefinitionSchema = z.object({
    widget_description: z.string().optional(),
    widget_prefers_border: z.boolean().optional(),
    widget_csp: z.object({
        connect_domains: z.array(z.string()).optional(),
        resource_domains: z.array(z.string()).optional()
    }).optional(),
    custom_meta: z.record(z.string(), z.unknown()).optional()
});

export const resourceCompletionVariableDefinitionSchema = z.object({
    source: z.union([z.literal("static"), z.literal("operation"), z.literal("composite_tool")]),
    values: z.array(z.string()).optional(),
    operation: z.string().optional(),
    composite_tool: z.string().optional(),
    result_path: z.string().optional(),
    label_path: z.string().optional(),
    value_path: z.string().optional(),
    parameter_mapping: z.record(z.string(), z.string()).optional()
});

export const compositeStepSchema = z.object({
    call: z.string(),
    store_as: z.string(),
    depends_on: z.array(z.string()).optional()
});

export const toolAppsDefinitionSchema = z.object({
    output_template_resource_uri: z.string().optional(),
    template_parameter_mapping: z.record(z.string(), z.string()).optional(),
    widget_accessible: z.boolean().optional(),
    tool_invocation_message: z.object({
        invoking: z.string().optional(),
        invoked: z.string().optional()
    }).optional(),
    invocation_text: z.object({
        invoking: z.string().optional(),
        invoked: z.string().optional()
    }).optional(),
    annotations: z.record(z.string(), z.unknown()).optional(),
    custom_meta: z.record(z.string(), z.unknown()).optional()
});

export const promptArgumentDefinitionSchema = z.object({
    name: z.string(),
    description: z.string().optional(),
    required: z.boolean().optional()
});

export const promptMessageRoleSchema = z.union([z.literal("user"), z.literal("assistant")]);

export const promptContentTemplateSchema = z.object({
    type: z.literal("text"),
    text: z.string()
});

export const parameterTypeSchema = z.union([z.literal("string"), z.literal("integer"), z.literal("number"), z.literal("boolean"), z.literal("array"), z.literal("object")]);

export const parameterDefinitionSchema = z.object({
    type: z.union([parameterTypeSchema, z.array(parameterTypeSchema)]),
    description: z.string(),
    required: z.boolean().optional(),
    required_for: z.array(z.string()).optional(),
    allowed_for: z.array(z.string()).optional(),
    forbidden_for: z.array(z.string()).optional(),
    enum: z.array(z.string()).optional(),
    enum_for: z.record(z.string(), z.array(z.string())).optional(),
    minLength: z.number().optional(),
    maxLength: z.number().optional(),
    pattern: z.string().optional(),
    items: z.object({
        type: z.string()
    }).optional(),
    properties: z.record(z.string(), z.unknown()).optional(),
    default: z.unknown().optional(),
    example: z.unknown().optional(),
    object_entries_to_array: z.object({
        key_field: z.string(),
        value_field: z.string(),
        wrap_value_field: z.string().optional()
    }).optional(),
    array_item_to_object: z.object({
        key_field: z.string()
    }).optional()
});

export const proxyDownloadOperationSchema = z.object({
    type: z.literal("proxy_download"),
    metadata_endpoint: z.string(),
    download_endpoint: z.string().optional(),
    url_field: z.string().optional(),
    max_size_bytes: z.number().optional(),
    max_size_bytes_from_env: z.string().optional(),
    timeout_ms: z.number().optional(),
    allowed_mime_types: z.array(z.string()).optional(),
    skip_auth: z.boolean().optional(),
    allowed_hosts: z.array(z.string()).optional(),
    allow_private_network: z.boolean().optional()
});

export const multipartOperationSchema = z.object({
    operationId: z.string(),
    file_field_name: z.string().optional()
});

export const operationDefinitionSchema = z.union([z.string(), proxyDownloadOperationSchema, multipartOperationSchema]);

export const baseUrlConfigSchema = z.object({
    value_from_env: z.string(),
    default: z.string().optional()
});

export const cacheConfigSchema = z.object({
    enabled: z.boolean().optional(),
    backend: z.union([z.literal("memory"), z.literal("redis")]).optional(),
    scope: z.union([z.literal("auto"), z.literal("public"), z.literal("private"), z.literal("session")]).optional(),
    allow_shared_with_auth: z.boolean().optional(),
    ttl_seconds: z.number().optional(),
    max_entries: z.number().optional(),
    max_memory_bytes: z.number().optional(),
    max_memory_bytes_from_env: z.string().optional(),
    methods: z.array(z.union([z.literal("GET"), z.literal("HEAD")])).optional(),
    vary_headers: z.array(z.string()).optional()
});

export const rateLimitConfigSchema = z.object({
    max_requests_per_minute: z.number(),
    overrides: z.record(z.string(), z.object({
        max_requests_per_minute: z.number()
    })).optional()
});

export const retryConfigSchema = z.object({
    max_attempts: z.number(),
    backoff_ms: z.array(z.number()),
    retry_on_status: z.array(z.number())
});

export const oAuthConfigSchema = z.object({
    issuer: z.string().optional(),
    authorization_endpoint: z.string().optional(),
    token_endpoint: z.string().optional(),
    client_id: z.string().optional(),
    client_secret: z.string().optional(),
    scopes: z.array(z.string()).optional(),
    redirect_uri: z.string().optional(),
    registration_endpoint: z.string().optional(),
    introspection_endpoint: z.string().optional(),
    revocation_endpoint: z.string().optional(),
    allowed_redirect_hosts: z.array(z.string()).optional(),
    allow_unregistered_clients: z.boolean().optional(),
    allowed_unregistered_redirect_uris: z.array(z.string()).optional()
});

export const sessionCookieConfigSchema = z.object({
    login_endpoint: z.string(),
    login_method: z.literal("POST").optional(),
    login_content_type: z.union([z.literal("application/json"), z.literal("application/x-www-form-urlencoded")]).optional(),
    username_field: z.string(),
    username_from_env: z.string(),
    password_field: z.string(),
    password_from_env: z.string(),
    login_static_headers: z.record(z.string(), z.string()).optional(),
    login_static_body: z.record(z.string(), z.string()).optional(),
    cookie_names: z.array(z.string()),
    login_allowed_hosts: z.array(z.string()).optional(),
    reauth_on_statuses: z.array(z.number()).optional(),
    failure_backoff_ms: z.number().optional(),
    expiry_skew_ms: z.number().optional()
});

export const enterpriseIssuerConfigSchema = z.object({
    issuer: z.string(),
    issuer_from_env: z.string().optional(),
    jwks_uri: z.string().optional(),
    jwks_uri_from_env: z.string().optional(),
    allowed_algs: z.array(z.union([z.literal("RS256"), z.literal("RS384"), z.literal("RS512"), z.literal("ES256"), z.literal("ES384"), z.literal("ES512")])).optional(),
    allowed_algs_from_env: z.string().optional(),
    allowed_kids: z.array(z.string()).optional(),
    clock_skew_seconds: z.number().optional(),
    require_signed_assertions: z.boolean().optional(),
    trust_mode: z.union([z.literal("discovery"), z.literal("explicit")]).optional()
});

export const enterpriseTokenExchangeConfigSchema = z.object({
    grant_type: z.literal("urn:ietf:params:oauth:grant-type:jwt-bearer"),
    subject_token_type: z.literal("urn:ietf:params:oauth:token-type:id_token").optional(),
    required_typ: z.array(z.string()).optional(),
    required_claims: z.array(z.string()).optional(),
    max_assertion_ttl_seconds: z.number().optional(),
    max_assertion_size_bytes: z.number().optional(),
    replay_protection_ttl_seconds: z.number().optional(),
    allowed_client_ids: z.array(z.string()).optional()
});

export const enterpriseAccessPolicyConfigSchema = z.object({
    claim_mappings: z.object({
        subject: z.string().optional(),
        email: z.string().optional(),
        groups: z.string().optional(),
        tenant_id: z.string().optional(),
        client_id: z.string().optional()
    }).optional(),
    claim_mappings_from_env: z.string().optional(),
    scopes_supported: z.array(z.string()).optional(),
    default_scopes: z.array(z.string()).optional(),
    default_scopes_from_env: z.string().optional(),
    required_scopes: z.array(z.string()).optional(),
    required_scopes_from_env: z.string().optional(),
    allowed_tool_categories: z.array(z.union([z.literal("list"), z.literal("read"), z.literal("modify"), z.literal("admin")])).optional(),
    allowed_tool_categories_from_env: z.string().optional(),
    allow_dynamic_client_registration: z.boolean().optional()
});

export const enterpriseMetadataConfigSchema = z.object({
    authorization_servers: z.array(z.string()).optional(),
    documentation_url: z.string().optional(),
    display_name: z.string().optional(),
    extensions: z.record(z.string(), z.union([z.string(), z.boolean(), z.number(), z.array(z.string())])).optional()
});

export const toolDefinitionSchema = z.object({
    name: z.string(),
    description: z.string(),
    operations: z.record(z.string(), operationDefinitionSchema).optional(),
    composite: z.boolean().optional(),
    steps: z.array(compositeStepSchema).optional(),
    partial_results: z.boolean().optional(),
    parameters: z.record(z.string(), parameterDefinitionSchema),
    metadata_params: z.array(z.string()).optional(),
    response_fields: z.record(z.string(), z.array(z.string())).optional(),
    send_response_fields_as_param: z.boolean().optional(),
    apps: toolAppsDefinitionSchema.optional()
});

export const enterpriseAuthorizationConfigSchema = z.object({
    enabled: z.boolean(),
    mode: z.union([z.literal("required"), z.literal("optional")]).optional(),
    mode_from_env: z.string().optional(),
    resource: z.string().optional(),
    audience: z.union([z.string(), z.array(z.string())]).optional(),
    audience_from_env: z.string().optional(),
    issuer: enterpriseIssuerConfigSchema,
    token_exchange: enterpriseTokenExchangeConfigSchema,
    access_policy: enterpriseAccessPolicyConfigSchema.optional(),
    metadata: enterpriseMetadataConfigSchema.optional()
});

export const upstreamMcpTransportConfigSchema = upstreamMcpHttpStreamableTransportConfigSchema;

export const resourceCompletionDefinitionSchema = z.object({
    variables: z.record(z.string(), resourceCompletionVariableDefinitionSchema)
});

export const promptMessageTemplateSchema = z.object({
    role: promptMessageRoleSchema,
    content: promptContentTemplateSchema
});

export const authInterceptorSchema = z.object({
    type: z.union([z.literal("bearer"), z.literal("token"), z.literal("query"), z.literal("custom-header"), z.literal("session-cookie"), z.literal("oauth")]),
    priority: z.number().optional(),
    header_name: z.string().optional(),
    query_param: z.string().optional(),
    value_from_env: z.string().optional(),
    oauth_config: oAuthConfigSchema.optional(),
    session_cookie_config: sessionCookieConfigSchema.optional(),
    oauth_rate_limit: z.object({
        max_requests: z.number(),
        window_ms: z.number()
    }).optional(),
    validation_endpoint: z.string().optional(),
    validation_method: z.union([z.literal("GET"), z.literal("HEAD")]).optional(),
    validation_timeout_ms: z.number().optional(),
    validation_allowed_hosts: z.array(z.string()).optional()
});

export const promptDefinitionSchema = z.object({
    name: z.string(),
    description: z.string().optional(),
    arguments: z.array(promptArgumentDefinitionSchema).optional(),
    messages: z.array(promptMessageTemplateSchema)
});

export const resourceDefinitionSchema = z.object({
    name: z.string(),
    kind: z.union([z.literal("static"), z.literal("template")]),
    uri: z.string().optional(),
    uri_template: z.string().optional(),
    title: z.string().optional(),
    description: z.string().optional(),
    mime_type: z.string(),
    file_path: z.string().optional(),
    inline_text: z.string().optional(),
    fetch: resourceFetchDefinitionSchema.optional(),
    completion: resourceCompletionDefinitionSchema.optional(),
    apps: resourceAppsDefinitionSchema.optional()
});

export const interceptorConfigSchema = z.object({
    auth: z.union([authInterceptorSchema, z.array(authInterceptorSchema)]).optional(),
    base_url: baseUrlConfigSchema.optional(),
    cache: cacheConfigSchema.optional(),
    rate_limit: rateLimitConfigSchema.optional(),
    retry: retryConfigSchema.optional(),
    array_format: z.union([z.literal("brackets"), z.literal("indices"), z.literal("repeat"), z.literal("comma")]).optional(),
    timeout_ms: z.number().optional(),
    redirect_auth_policy: z.union([z.literal("same-origin"), z.literal("never")]).optional()
});

export const upstreamMcpServerConfigSchema = z.object({
    name: z.string(),
    transport: upstreamMcpTransportConfigSchema,
    auth: upstreamMcpAuthConfigSchema.optional(),
    tool_prefix: z.string().optional(),
    tools: upstreamMcpToolPolicySchema.optional(),
    timeout_ms: z.number().optional(),
    html_description_policy: z.union([z.literal("allow"), z.literal("strip"), z.literal("drop")]).optional(),
    tool_description_length_policy: z.union([z.literal("drop"), z.literal("truncate"), z.literal("allow")]).optional(),
    validation_endpoint: z.string().optional(),
    validation_method: z.union([z.literal("HEAD"), z.literal("GET")]).optional(),
    validation_timeout_ms: z.number().optional()
});

export const profileSchema = z.object({
    profile_name: z.string(),
    profile_id: z.string().optional(),
    profile_aliases: z.array(z.string()).optional(),
    openapi_spec_path: z.string().optional(),
    description: z.string().optional(),
    tools: z.array(toolDefinitionSchema),
    prompts: z.array(promptDefinitionSchema).optional(),
    resources: z.array(resourceDefinitionSchema).optional(),
    interceptors: interceptorConfigSchema.optional(),
    parameter_aliases: z.record(z.string(), z.array(z.string())).optional(),
    enterprise_authorization: enterpriseAuthorizationConfigSchema.optional(),
    client_auth_gate: clientAuthGateConfigSchema.optional(),
    consent_gate: consentGateConfigSchema.optional(),
    upstream_mcp: upstreamMcpServerConfigSchema.optional(),
    upstream_mcp_from_env: z.string().optional(),
    resource_name: z.string().optional(),
    resource_documentation: z.string().optional()
});
