// Generated by ts-to-zod
import { z } from "zod";

export const compositeStepSchema = z.object({
    call: z.string(),
    store_as: z.string(),
    depends_on: z.array(z.string()).optional()
});

export const parameterTypeSchema = z.union([z.literal("string"), z.literal("integer"), z.literal("number"), z.literal("boolean"), z.literal("array"), z.literal("object")]);

export const parameterDefinitionSchema = z.object({
    type: z.union([parameterTypeSchema, z.array(parameterTypeSchema)]),
    description: z.string(),
    required: z.boolean().optional(),
    required_for: z.array(z.string()).optional(),
    enum: z.array(z.string()).optional(),
    items: z.object({
        type: z.string()
    }).optional(),
    properties: z.record(z.string(), z.unknown()).optional(),
    default: z.unknown().optional(),
    example: z.unknown().optional(),
    object_entries_to_array: z.object({
        key_field: z.string(),
        value_field: z.string(),
        wrap_value_field: z.string().optional()
    }).optional(),
    array_item_to_object: z.object({
        key_field: z.string()
    }).optional()
});

export const proxyDownloadOperationSchema = z.object({
    type: z.literal("proxy_download"),
    metadata_endpoint: z.string(),
    download_endpoint: z.string().optional(),
    url_field: z.string().optional(),
    max_size_bytes: z.number().optional(),
    max_size_bytes_from_env: z.string().optional(),
    timeout_ms: z.number().optional(),
    allowed_mime_types: z.array(z.string()).optional(),
    skip_auth: z.boolean().optional(),
    allowed_hosts: z.array(z.string()).optional(),
    allow_private_network: z.boolean().optional()
});

export const operationDefinitionSchema = z.union([z.string(), proxyDownloadOperationSchema]);

export const baseUrlConfigSchema = z.object({
    value_from_env: z.string(),
    default: z.string().optional()
});

export const rateLimitConfigSchema = z.object({
    max_requests_per_minute: z.number(),
    overrides: z.record(z.string(), z.object({
        max_requests_per_minute: z.number()
    })).optional()
});

export const retryConfigSchema = z.object({
    max_attempts: z.number(),
    backoff_ms: z.array(z.number()),
    retry_on_status: z.array(z.number())
});

export const oAuthConfigSchema = z.object({
    issuer: z.string().optional(),
    authorization_endpoint: z.string().optional(),
    token_endpoint: z.string().optional(),
    client_id: z.string().optional(),
    client_secret: z.string().optional(),
    scopes: z.array(z.string()).optional(),
    redirect_uri: z.string().optional(),
    registration_endpoint: z.string().optional(),
    introspection_endpoint: z.string().optional(),
    revocation_endpoint: z.string().optional(),
    allowed_redirect_hosts: z.array(z.string()).optional()
});

export const toolDefinitionSchema = z.object({
    name: z.string(),
    description: z.string(),
    operations: z.record(z.string(), operationDefinitionSchema).optional(),
    composite: z.boolean().optional(),
    steps: z.array(compositeStepSchema).optional(),
    partial_results: z.boolean().optional(),
    parameters: z.record(z.string(), parameterDefinitionSchema),
    metadata_params: z.array(z.string()).optional(),
    response_fields: z.record(z.string(), z.array(z.string())).optional(),
    send_response_fields_as_param: z.boolean().optional()
});

export const authInterceptorSchema = z.object({
    type: z.union([z.literal("bearer"), z.literal("query"), z.literal("custom-header"), z.literal("oauth")]),
    priority: z.number().optional(),
    header_name: z.string().optional(),
    query_param: z.string().optional(),
    value_from_env: z.string().optional(),
    oauth_config: oAuthConfigSchema.optional(),
    oauth_rate_limit: z.object({
        max_requests: z.number(),
        window_ms: z.number()
    }).optional(),
    validation_endpoint: z.string().optional(),
    validation_method: z.union([z.literal("GET"), z.literal("HEAD")]).optional(),
    validation_timeout_ms: z.number().optional()
});

export const interceptorConfigSchema = z.object({
    auth: z.union([authInterceptorSchema, z.array(authInterceptorSchema)]).optional(),
    base_url: baseUrlConfigSchema.optional(),
    rate_limit: rateLimitConfigSchema.optional(),
    retry: retryConfigSchema.optional(),
    array_format: z.union([z.literal("brackets"), z.literal("indices"), z.literal("repeat"), z.literal("comma")]).optional()
});

export const profileSchema = z.object({
    profile_name: z.string(),
    profile_id: z.string().optional(),
    profile_aliases: z.array(z.string()).optional(),
    openapi_spec_path: z.string().optional(),
    description: z.string().optional(),
    tools: z.array(toolDefinitionSchema),
    interceptors: interceptorConfigSchema.optional(),
    parameter_aliases: z.record(z.string(), z.array(z.string())).optional(),
    resource_name: z.string().optional(),
    resource_documentation: z.string().optional()
});
