// Generated by ts-to-zod
import { z } from "zod";

export const resourceFetchDefinitionSchema = z.object({
    source: z.union([z.literal("operation"), z.literal("composite")]),
    operation: z.string().optional(),
    composite_tool: z.string().optional(),
    parameter_mapping: z.record(z.string(), z.string()).optional(),
    result_path: z.string().optional(),
    cache_ttl_seconds: z.number().optional()
});

export const resourceAppsDefinitionSchema = z.object({
    widget_description: z.string().optional(),
    widget_prefers_border: z.boolean().optional(),
    widget_csp: z.object({
        connect_domains: z.array(z.string()).optional(),
        resource_domains: z.array(z.string()).optional()
    }).optional(),
    custom_meta: z.record(z.string(), z.unknown()).optional()
});

export const resourceCompletionVariableDefinitionSchema = z.object({
    source: z.union([z.literal("static"), z.literal("operation"), z.literal("composite_tool")]),
    values: z.array(z.string()).optional(),
    operation: z.string().optional(),
    composite_tool: z.string().optional(),
    result_path: z.string().optional(),
    label_path: z.string().optional(),
    value_path: z.string().optional(),
    parameter_mapping: z.record(z.string(), z.string()).optional()
});

export const compositeStepSchema = z.object({
    call: z.string(),
    store_as: z.string(),
    depends_on: z.array(z.string()).optional()
});

export const toolAppsDefinitionSchema = z.object({
    output_template_resource_uri: z.string().optional(),
    widget_accessible: z.boolean().optional(),
    tool_invocation_message: z.object({
        invoking: z.string().optional(),
        invoked: z.string().optional()
    }).optional(),
    invocation_text: z.object({
        invoking: z.string().optional(),
        invoked: z.string().optional()
    }).optional(),
    annotations: z.record(z.string(), z.unknown()).optional(),
    custom_meta: z.record(z.string(), z.unknown()).optional()
});

export const promptArgumentDefinitionSchema = z.object({
    name: z.string(),
    description: z.string().optional(),
    required: z.boolean().optional()
});

export const promptMessageRoleSchema = z.union([z.literal("user"), z.literal("assistant")]);

export const promptContentTemplateSchema = z.object({
    type: z.literal("text"),
    text: z.string()
});

export const parameterTypeSchema = z.union([z.literal("string"), z.literal("integer"), z.literal("number"), z.literal("boolean"), z.literal("array"), z.literal("object")]);

export const parameterDefinitionSchema = z.object({
    type: z.union([parameterTypeSchema, z.array(parameterTypeSchema)]),
    description: z.string(),
    required: z.boolean().optional(),
    required_for: z.array(z.string()).optional(),
    allowed_for: z.array(z.string()).optional(),
    forbidden_for: z.array(z.string()).optional(),
    enum: z.array(z.string()).optional(),
    enum_for: z.record(z.string(), z.array(z.string())).optional(),
    minLength: z.number().optional(),
    maxLength: z.number().optional(),
    pattern: z.string().optional(),
    items: z.object({
        type: z.string()
    }).optional(),
    properties: z.record(z.string(), z.unknown()).optional(),
    default: z.unknown().optional(),
    example: z.unknown().optional(),
    object_entries_to_array: z.object({
        key_field: z.string(),
        value_field: z.string(),
        wrap_value_field: z.string().optional()
    }).optional(),
    array_item_to_object: z.object({
        key_field: z.string()
    }).optional()
});

export const proxyDownloadOperationSchema = z.object({
    type: z.literal("proxy_download"),
    metadata_endpoint: z.string(),
    download_endpoint: z.string().optional(),
    url_field: z.string().optional(),
    max_size_bytes: z.number().optional(),
    max_size_bytes_from_env: z.string().optional(),
    timeout_ms: z.number().optional(),
    allowed_mime_types: z.array(z.string()).optional(),
    skip_auth: z.boolean().optional(),
    allowed_hosts: z.array(z.string()).optional(),
    allow_private_network: z.boolean().optional()
});

export const operationDefinitionSchema = z.union([z.string(), proxyDownloadOperationSchema]);

export const baseUrlConfigSchema = z.object({
    value_from_env: z.string(),
    default: z.string().optional()
});

export const cacheConfigSchema = z.object({
    enabled: z.boolean().optional(),
    backend: z.union([z.literal("memory"), z.literal("redis")]).optional(),
    scope: z.union([z.literal("auto"), z.literal("public"), z.literal("private"), z.literal("session")]).optional(),
    allow_shared_with_auth: z.boolean().optional(),
    ttl_seconds: z.number().optional(),
    max_entries: z.number().optional(),
    max_memory_bytes: z.number().optional(),
    max_memory_bytes_from_env: z.string().optional(),
    methods: z.array(z.union([z.literal("GET"), z.literal("HEAD")])).optional(),
    vary_headers: z.array(z.string()).optional()
});

export const rateLimitConfigSchema = z.object({
    max_requests_per_minute: z.number(),
    overrides: z.record(z.string(), z.object({
        max_requests_per_minute: z.number()
    })).optional()
});

export const retryConfigSchema = z.object({
    max_attempts: z.number(),
    backoff_ms: z.array(z.number()),
    retry_on_status: z.array(z.number())
});

export const oAuthConfigSchema = z.object({
    issuer: z.string().optional(),
    authorization_endpoint: z.string().optional(),
    token_endpoint: z.string().optional(),
    client_id: z.string().optional(),
    client_secret: z.string().optional(),
    scopes: z.array(z.string()).optional(),
    redirect_uri: z.string().optional(),
    registration_endpoint: z.string().optional(),
    introspection_endpoint: z.string().optional(),
    revocation_endpoint: z.string().optional(),
    allowed_redirect_hosts: z.array(z.string()).optional()
});

export const sessionCookieConfigSchema = z.object({
    login_endpoint: z.string(),
    login_method: z.literal("POST").optional(),
    login_content_type: z.union([z.literal("application/json"), z.literal("application/x-www-form-urlencoded")]).optional(),
    username_field: z.string(),
    username_from_env: z.string(),
    password_field: z.string(),
    password_from_env: z.string(),
    login_static_headers: z.record(z.string(), z.string()).optional(),
    login_static_body: z.record(z.string(), z.string()).optional(),
    cookie_names: z.array(z.string()),
    login_allowed_hosts: z.array(z.string()).optional(),
    reauth_on_statuses: z.array(z.number()).optional(),
    failure_backoff_ms: z.number().optional(),
    expiry_skew_ms: z.number().optional()
});

export const toolDefinitionSchema = z.object({
    name: z.string(),
    description: z.string(),
    operations: z.record(z.string(), operationDefinitionSchema).optional(),
    composite: z.boolean().optional(),
    steps: z.array(compositeStepSchema).optional(),
    partial_results: z.boolean().optional(),
    parameters: z.record(z.string(), parameterDefinitionSchema),
    metadata_params: z.array(z.string()).optional(),
    response_fields: z.record(z.string(), z.array(z.string())).optional(),
    send_response_fields_as_param: z.boolean().optional(),
    apps: toolAppsDefinitionSchema.optional()
});

export const resourceCompletionDefinitionSchema = z.object({
    variables: z.record(z.string(), resourceCompletionVariableDefinitionSchema)
});

export const promptMessageTemplateSchema = z.object({
    role: promptMessageRoleSchema,
    content: promptContentTemplateSchema
});

export const authInterceptorSchema = z.object({
    type: z.union([z.literal("bearer"), z.literal("query"), z.literal("custom-header"), z.literal("session-cookie"), z.literal("oauth")]),
    priority: z.number().optional(),
    header_name: z.string().optional(),
    query_param: z.string().optional(),
    value_from_env: z.string().optional(),
    oauth_config: oAuthConfigSchema.optional(),
    session_cookie_config: sessionCookieConfigSchema.optional(),
    oauth_rate_limit: z.object({
        max_requests: z.number(),
        window_ms: z.number()
    }).optional(),
    validation_endpoint: z.string().optional(),
    validation_method: z.union([z.literal("GET"), z.literal("HEAD")]).optional(),
    validation_timeout_ms: z.number().optional(),
    validation_allowed_hosts: z.array(z.string()).optional()
});

export const promptDefinitionSchema = z.object({
    name: z.string(),
    description: z.string().optional(),
    arguments: z.array(promptArgumentDefinitionSchema).optional(),
    messages: z.array(promptMessageTemplateSchema)
});

export const resourceDefinitionSchema = z.object({
    name: z.string(),
    kind: z.union([z.literal("static"), z.literal("template")]),
    uri: z.string().optional(),
    uri_template: z.string().optional(),
    title: z.string().optional(),
    description: z.string().optional(),
    mime_type: z.string(),
    file_path: z.string().optional(),
    inline_text: z.string().optional(),
    fetch: resourceFetchDefinitionSchema.optional(),
    completion: resourceCompletionDefinitionSchema.optional(),
    apps: resourceAppsDefinitionSchema.optional()
});

export const interceptorConfigSchema = z.object({
    auth: z.union([authInterceptorSchema, z.array(authInterceptorSchema)]).optional(),
    base_url: baseUrlConfigSchema.optional(),
    cache: cacheConfigSchema.optional(),
    rate_limit: rateLimitConfigSchema.optional(),
    retry: retryConfigSchema.optional(),
    array_format: z.union([z.literal("brackets"), z.literal("indices"), z.literal("repeat"), z.literal("comma")]).optional(),
    timeout_ms: z.number().optional(),
    redirect_auth_policy: z.union([z.literal("same-origin"), z.literal("never")]).optional()
});

export const profileSchema = z.object({
    profile_name: z.string(),
    profile_id: z.string().optional(),
    profile_aliases: z.array(z.string()).optional(),
    openapi_spec_path: z.string().optional(),
    description: z.string().optional(),
    tools: z.array(toolDefinitionSchema),
    prompts: z.array(promptDefinitionSchema).optional(),
    resources: z.array(resourceDefinitionSchema).optional(),
    interceptors: interceptorConfigSchema.optional(),
    parameter_aliases: z.record(z.string(), z.array(z.string())).optional(),
    resource_name: z.string().optional(),
    resource_documentation: z.string().optional()
});
